# Generated by Django 5.1.5 on 2025-02-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleItemOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(max_length=512)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_item_order_payments', to='orders.vehicleitemorder')),
            ],
            options={
                'verbose_name': 'Vehicle Item Order Payment',
                'verbose_name_plural': 'Vehicle Item Order Payments',
            },
        ),
    ]
