# Generated by Django 5.1.5 on 2025-02-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('body_style', models.CharField(blank=True, max_length=512, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=512, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
