# Generated by Django 5.1.5 on 2025-02-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardetails',
            options={'verbose_name': 'Car Details', 'verbose_name_plural': 'Car Details'},
        ),
    ]
