# Generated by Django 5.1.5 on 2025-02-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_cardetails_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleItemInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('code', models.CharField(db_index=True, max_length=512, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_quantity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Vehicle Item Inventory',
                'verbose_name_plural': 'Vehicle Item Inventories',
            },
        ),
    ]
