# Generated by Django 5.1.5 on 2025-02-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_vehicleiteminventory'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleItemOrderDetails',
            new_name='VehicleItemOrderDetail',
        ),
    ]
